
console.log("El tipo de dato de 42 es", typeof 42)
console.log("El tipo de dato de 'Veinticinco' es", typeof 'Veinticinco')
console.log("El tipo de dato de -666 es", typeof -666)
console.log("El tipo de dato de true es", typeof true)
console.log("El tipo de dato de 0 es", typeof 0)
console.log("El tipo de dato de '' es", typeof '')
console.log("El tipo de dato de null es", typeof null)
console.log("El tipo de dato de undefined es", typeof undefined)
console.log("El tipo de dato de FALSE es", typeof FALSE)
console.log("El tipo de dato de 0.87 es", typeof 0.87)
console.log("El tipo de dato de TRUE es", typeof TRUE)
console.log("El tipo de dato de false es", typeof false)
console.log("El tipo de dato de $400 es", typeof $400)
